research_chapter:
  description: >
    Research the provided chapter topic, title, and outline.
    We always focus on reliable, high-quality sources of information.

    Desired goal:\n\n {goal}
    Chapter description:\n\n {chapter_description}

    When researching, you:
    - gather enough information to write a 3,000-word chapter
    - The chapter you are researching needs to fit in with the rest of the book.

    Outline of the entire book:\n\n
    {book_outline}
  expected_output: >
    A comprehensive list of additional insights or information that can be used in writing the chapter.
  agent: researcher

write_chapter:
  description: >
    Write a well-structured chapter based on the chapter title, goal, and outline description. 
    Each chapter should be written in markdown and should contain around 3,000 words.

    Here is the topic for the book: {topic}
    Here is the title of the chapter: {chapter_title}
    Here is the outline description for the chapter:\n\n {chapter_description}

    The chapter you are writing needs to fit in well with the rest of the chapters in the book:\n\n
    {book_outline}
  expected_output: >
    A markdown-formatted chapter of around 3,000 words that covers the provided chapter title and outline description.
  agent: writer
